channels:
- conda-forge
dependencies:
- python=3.10.9
- pip<=22.3.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==2.0.0
  - lz4==4.3.2
  - numpy==1.23.5
  - packaging==22.0
  - pandas==1.5.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.2.1
  - scipy==1.11.3
  - xgboost==1.7.6
name: mlflow-env
