name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install jupytext
    
    - name: Convert jupyter files to py files
      run: |
        jupytext --to py $(git ls-files '*.ipynb')

    - name: Run pylint
      run: |
        pylint --recursive=y *.py **/*.py **/**/*.py **/**/**/*.py --disable=C0303, C0304, C0301, R1710, E0401,W0404, C0411 ,C0301,C0413,W0613 --fail-under=8

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      run: |
        python ./develop/data_retrieval.py
